language: php

matrix:
  include:
    - php: 5.6
      env: PREFER_LOWEST=--prefer-lowest
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
      env: COLLECT_COVERAGE=true

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit

after_script:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.xml; fi
