language: php
os: linux
dist: xenial

jobs:
  include:
    - php: 7.3
      env: PREFER_LOWEST=--prefer-lowest
    - php: 7.4
    - php: 8.0
    - php: 8.1
      env: COLLECT_COVERAGE=true

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction
  - travis_retry composer update $PREFER_LOWEST

script:
  - vendor/bin/phpunit

after_success:
  - if [[ "$COLLECT_COVERAGE" == "true" ]]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.xml; fi
